import "./globals.css"
import { Inter } from "next/font/google"
import { Analytics } from "@vercel/analytics/react"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Timetable Generator",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        {children}
        <Analytics />
        <footer className="w-full flex justify-center mb-12 text-[0.8em] font-semibold text-gray-300 mt-48">&#169; {new Date().getFullYear()}</footer>
      </body>
    </html>
  )
}
